### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by CreamyLong** [pbsinclair42/MCTS#11]
Hi, Thanks for your great work. When I run your example **NaughtsAndCrossesState**, I get the info that is AttributeError: 'NoneType' object has no attribute 'state'

**Comment by CreamyLong** [comment]
I found that when I set timeLimit or iterationLimit low the program was ok, but when the values are high the error comes out

**Comment by WhymustIhaveaname** [comment]
This is because he uses the same name for class `mcts` and the object `mcts`.
```
mcts = mcts(timeLimit=1000)
bestAction = mcts.search(initialState=initialState)
```
Change it into
```
searcher = mcts(timeLimit=1000)
action = searcher.search(initialState=initialState)
```
will solve this issue. I also correct this in [pull request #13](https://github.com/pbsinclair42/MCTS/pull/13).
