### ISSUE TITLE
naughtsandcrosses not playing optimally

### ISSUE THREAD

**Issue by taylorvance** [pbsinclair42/MCTS#12]
I'm trying out your code, just expanding on your demo. I set up the computer to play itself, but it's not doing a very good job, even when I extend the time limit from 1 second to 10. X almost always wins. Any idea why? Am I running the code wrong, or is there something wrong with your algorithm and/or naughtsandcrosses implementation?

I can share my NaughtsAndCrossesState.renderBoard() code if you'd like. Everything else is unchanged from your code.

```
mcts = mcts(timeLimit=1000)

state = NaughtsAndCrossesState()
print(state.renderBoard())

while not state.isTerminal():
    action = mcts.search(state)
    state = state.takeAction(action)
    print(state.renderBoard())
```

**Comment by WhymustIhaveaname** [comment]
I will have a look at it soon.

**Comment by WhymustIhaveaname** [comment]
I know it is impolite to say, but I have to say, it works on my machine. I tested it twice. Firstly, I let it play with itself.
```
searcher=mcts(timeLimit=1000)
gamestate=NaughtsAndCrossesState()
while not gamestate.isTerminal():
    action=searcher.search(initialState=gamestate)
    print("player %2d played %s"%(gamestate.getCurrentPlayer(),action))
    gamestate=gamestate.takeAction(action)
print("game over, result: %s"%(gamestate.getReward()))
```
Then, I test it with some must-win scenarios.
```
searcher=mcts(timeLimit=1000)
gamestate=NaughtsAndCrossesState()
gamestate.board=[[1,1,0],[-1,-1,0],[0,0,0]]
action=searcher.search(initialState=gamestate)
print("player %2d played %s"%(gamestate.getCurrentPlayer(),action))
gamestate=gamestate.takeAction(action)
assert gamestate.isTerminal()
print("result: %s"%(gamestate.getReward()))
```
It always gives me the best choice. Can you share at which board situation it breaks?

**Comment by pbsinclair42** [comment]
Can you also confirm which version of the package you were using when you found the above? I'm also unable to reproduce this I'm afraid.

**Comment by pbsinclair42** [comment]
Closing this due to no response, feel free to comment if this issue persists.

**Comment by acmol** [comment]
reproduce this too.
I install this lib with pip install, then download the demo naughtsandcrossses, then reproduced this bug.

Name: mcts
Version: 1.0.4
Summary: A simple package to allow users to run Monte Carlo Tree Search on any perfect information domain
Home-page: https://github.com/pbsinclair42/MCTS
Author: Paul Sinclair
Author-email: pbsinclair42@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by:

**Comment by acmol** [comment]
I found the reason.

The code installed by "pip install" has a bug fixed in master branch. 

https://github.com/pbsinclair42/MCTS/pull/10
