### ISSUE TITLE
Why does NaughtsAndCrossesState not play so well?

### ISSUE THREAD

**Issue by huzujun** [pbsinclair42/MCTS#2]
I play with the AI, but it seems not to play so well in this easy game.
For example, 
```
    def __init__(self):
        self.board = [[1, -1, 0], 
                             [1,  1, 0], 
                             [-1, 0, -1]]
        self.currentPlayer = 1
```
I think humans will definitely choose (1,2), but the code seem to usually choose (0, 2)
Is my operation wrong?Or what caused it to rush the wrong way.

**Comment by pbsinclair42** [comment]
You're right, this was due to a bug in the getBestChild function [as spotted by @mrtolkiein](https://github.com/pbsinclair42/MCTS/issues/3).  I've pushed a change to fix this; good luck beating the AI now!
