### ISSUE TITLE
Not entirely understanding the getBestChild function

### ISSUE THREAD

**Issue by mrtolkien** [pbsinclair42/MCTS#3]
```
    def getBestChild(self, node, explorationValue):
        bestValue = float("-inf")
        bestNodes = []
        for child in node.children.values():
            nodeValue = child.totalReward / child.numVisits + explorationValue * math.sqrt(
                2 * math.log(node.numVisits) / child.numVisits)
            if nodeValue >= bestValue:
                bestValue = nodeValue
                bestNodes.append(child)
        return random.choice(bestNodes)

```
This implementation looks like it will always append at least the first child it explores to bestNodes, which means it could be selected at random at the end, right?

I might be misunderstanding the process, but that might explain the performance issues raised by the other poster.

**Comment by pbsinclair42** [comment]
You're entirely correct, good spot!  I've pushed a change to fix that now.  Thanks!

**Comment by esparano** [comment]
@pbsinclair42 Could you update the pypi version to take this fix into account? Thanks.
https://pypi.org/project/mcts/

**Comment by pbsinclair42** [comment]
Sure, I've published this fix in pypi now too, apologies for not doing this sooner!

**Comment by esparano** [comment]
No problem, thanks!!
