### ISSUE TITLE
Feature request: have more information returned with the action chosen

### ISSUE THREAD

**Issue by DarioBernardo** [pbsinclair42/MCTS#7]
Hi, thank you for your great work. Is it possible to have more information returned with the action chosen? like probability of success, expected reward or anything that could be interesting? thank you

**Comment by DarioBernardo** [comment]
Let `totalReward / numVisit` be `avg_reward_per_visit` 
Do you think that `best child` `avg_reward_per_visit`  / `sum of all childs` `avg_reward_per_visit` 
can give some sort of confidence in the choice ?
Thanks

**Comment by DarioBernardo** [comment]
Hi, I hope my comment is clear, or maybe a bit more explanation is needed?

**Comment by pbsinclair42** [comment]
Hi Dario,

Thanks for the request, aye, it's clear.  I'm afraid I don't have the bandwidth to work on this myself right now though, but feel free to make a pull request and I'll take a look :)

**Comment by DarioBernardo** [comment]
Yeah I can do that, no problem, but do you think the logic I've mentioned makes sense? it is a bit of a hack, and it is not backed by any theory :)

**Comment by WhymustIhaveaname** [comment]
I am going to add this feature very soon. I am writing a card AI where I need this feature.

**Comment by WhymustIhaveaname** [comment]
I add a parameter `needNodeValue=False` in `search`. If it is set to `True`, `search` will return the best action and NodeValue, which is the best node's average value. If it is kept `False`, as default, `search` will keep its original behavior, making it backward compatible. I will push from my fork to this repo as soon as I finish the tests.

**Comment by WhymustIhaveaname** [comment]
I have added this feature in [my fork](https://github.com/Gongzhu-Society/MCTS) and pushed my branch to [pull request #13](https://github.com/pbsinclair42/MCTS/pull/13).
